# Generated by Django 4.2.4 on 2023-09-23 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0006_rename_emailuser_login_e'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('boytext', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Login_E',
        ),
    ]
