# Generated by Django 4.2.4 on 2023-10-01 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0010_rename_footertext_page_setting_footer_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Create_Acct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fname', models.CharField(default='hmmmed', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='page_setting',
            name='Lname',
            field=models.CharField(default='adepoju', max_length=200),
        ),
        migrations.AddField(
            model_name='page_setting',
            name='password',
            field=models.CharField(default='hammed', max_length=200),
        ),
        migrations.AddField(
            model_name='page_setting',
            name='picture',
            field=models.ImageField(default='assets/img/logo.png', upload_to='assets/img/'),
        ),
        migrations.AddField(
            model_name='page_setting',
            name='user_type',
            field=models.CharField(default='visitor', max_length=200),
        ),
        migrations.AddField(
            model_name='page_setting',
            name='username',
            field=models.CharField(default='adppoju', max_length=200),
        ),
        migrations.AlterField(
            model_name='page_setting',
            name='address',
            field=models.EmailField(default='ayekale', max_length=200),
        ),
        migrations.AlterField(
            model_name='page_setting',
            name='email',
            field=models.EmailField(default='hammed@gmail.com', max_length=200),
        ),
    ]
