# Generated by Django 4.2.4 on 2023-10-01 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0011_create_acct_page_setting_lname_page_setting_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page_setting',
            name='Lname',
        ),
        migrations.RemoveField(
            model_name='page_setting',
            name='password',
        ),
        migrations.RemoveField(
            model_name='page_setting',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='page_setting',
            name='user_type',
        ),
        migrations.RemoveField(
            model_name='page_setting',
            name='username',
        ),
        migrations.AddField(
            model_name='create_acct',
            name='Lname',
            field=models.CharField(default='adepoju', max_length=200),
        ),
        migrations.AddField(
            model_name='create_acct',
            name='address',
            field=models.EmailField(default='ayekale', max_length=200),
        ),
        migrations.AddField(
            model_name='create_acct',
            name='email',
            field=models.EmailField(default='hammed@gmail.com', max_length=200),
        ),
        migrations.AddField(
            model_name='create_acct',
            name='password',
            field=models.CharField(default='hammed', max_length=200),
        ),
        migrations.AddField(
            model_name='create_acct',
            name='picture',
            field=models.ImageField(default='assets/img/logo.png', upload_to='assets/img/'),
        ),
        migrations.AddField(
            model_name='create_acct',
            name='user_type',
            field=models.CharField(default='visitor', max_length=200),
        ),
        migrations.AddField(
            model_name='create_acct',
            name='username',
            field=models.CharField(default='adppoju', max_length=200),
        ),
        migrations.AlterField(
            model_name='page_setting',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='page_setting',
            name='email',
            field=models.EmailField(max_length=200),
        ),
    ]
