# Generated by Django 4.2.4 on 2023-10-02 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0013_bot_acct_create_company_open_ai'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bot_acct',
            name='intense',
        ),
        migrations.AddField(
            model_name='bot_acct',
            name='dialogflow',
            field=models.URLField(null=True),
        ),
    ]
