# Generated by Django 4.2.4 on 2023-10-18 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0014_remove_bot_acct_intense_bot_acct_dialogflow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page_setting',
            name='admin_login_image',
            field=models.ImageField(default='assets/img/logo.png', upload_to='main/img'),
        ),
        migrations.AlterField(
            model_name='page_setting',
            name='admin_page_logo',
            field=models.ImageField(default='assets/img/logo.png', upload_to='main/img'),
        ),
        migrations.AlterField(
            model_name='page_setting',
            name='favicon',
            field=models.ImageField(default='assets/img/logo.png', upload_to='main/img'),
        ),
        migrations.AlterField(
            model_name='page_setting',
            name='login_page_logo',
            field=models.ImageField(default='assets/img/logo.png', upload_to='main/img'),
        ),
    ]
