# Generated by Django 4.2.4 on 2023-10-19 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0015_alter_page_setting_admin_login_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page_setting',
            name='admin_login_image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='page_setting',
            name='admin_page_logo',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='page_setting',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='page_setting',
            name='login_page_logo',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
